# Generated by Django 5.2.3 on 2025-06-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='اسم الموقع')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='بريد التواصل')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='شعار الموقع')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'الإعدادات',
            },
        ),
    ]
